version: "3.8"

services:
  db-init:
    build:
      context: .
      dockerfile: Dockerfile  # Use the same Dockerfile for all services
    container_name: db-init
    working_dir: /fineract
    entrypoint: >
      bash -c "
      echo 'Creating databases...';
      cd /fineract;
      ./gradlew createDB -PdbName=fineract_tenants;
      ./gradlew createDB -PdbName=fineract_default;
      echo 'Databases created successfully.';"
    environment:
      FINERACT_DB_URL: jdbc:postgresql://ffdashboard.cn6yom60ugil.ap-south-1.rds.amazonaws.com:5432/
      FINERACT_DB_USERNAME: postgres
      FINERACT_DB_PASSWORD: mguqAKTTOFbDYpplilek
    networks:
      - fineract-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Use the same Dockerfile for all services
    container_name: fineract-backend
    working_dir: /fineract
    entrypoint: >
      bash -c "
      echo 'Starting backend...';
      cd /fineract;
      ./gradlew bootRun;"
    environment:
      FINERACT_DB_URL: jdbc:postgresql://ffdashboard.cn6yom60ugil.ap-south-1.rds.amazonaws.com:5432/
      FINERACT_DB_USERNAME: postgres
      FINERACT_DB_PASSWORD: mguqAKTTOFbDYpplilek
    ports:
      - "8080:8080"
    networks:
      - fineract-network

networks:
  fineract-network:
    driver: bridge
