version: "3.8"

services:
  db-init:
    build:
      context: .
      dockerfile: Dockerfile  # Use the same Dockerfile for all services
    container_name: db-init
    working_dir: /fineract
    entrypoint: >
      bash -c "
      echo 'Creating databases...';
      chmod +x ./gradlew;  # Ensure gradlew is executable
      mysql -h mysqlcontainer-mysql -u root -pmysql -e 'CREATE DATABASE IF NOT EXISTS fineract_tenants;';
      mysql -h mysqlcontainer-mysql -u root -pmysql -e 'CREATE DATABASE IF NOT EXISTS fineract_default;';
      echo 'Databases created successfully.';"
    environment:
      MYSQL_ROOT_PASSWORD: mysql  # Password for the MySQL root user
    networks:
      - fineract-network
    depends_on:
      - mysqlcontainer-mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Use the same Dockerfile for all services
    container_name: fineract-backend
    working_dir: /fineract
    entrypoint: >
      bash -c "
      echo 'Starting backend...';
      chmod +x ./gradlew;  # Ensure gradlew is executable
      ./gradlew bootRun; # Start the backend service"
    environment:
      FINERACT_DB_URL: jdbc:mysql://mysqlcontainer-mysql:3306/
      FINERACT_DB_USERNAME: root
      FINERACT_DB_PASSWORD: mysql
    ports:
      - "8080:8080"
    networks:
      - fineract-network
    depends_on:
      - mysqlcontainer-mysql

  mysqlcontainer-mysql:
    image: mysql:latest
    container_name: mysqlcontainer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks:
      - fineract-network
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

networks:
  fineract-network:
    driver: bridge

volumes:
  mysql-data:
